### ISSUE TITLE
Accordion Menu Bugs

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#121]
### Overview
"Once you’ve tapped on a main menu item, opening up the secondary menu, you can’t return to the top level menu – the only way to get out of the secondary menu you’ve opened is to tap (and expand) a main menu entry above the one you’re on. If you’re at the top of the main menu list (tapped “About”), then there’s no way back to the main menu, other than to “X” out of the menu altogether, and then re-open it." - Client

Client also noted that Android works better than IOS.

### Tasks
- [x] Differentiate main menu item and secondary menu item (sometimes the main menu items changes colour, but other times it doesn't
- [x] Secondary menu items only navigate to the section when clicked on the name and not the entire field 
- [x] On tablet view: remove blue background from centre of menu (screenshot below)
- [x] When on pages, clicking on the accordion menu opens but does not close the section
- [ ] On Impact page, when opening up sections it doesn't hold the position

**Comment by sovetsch** [comment]
<img width="305" alt="screen shot 2018-01-13 at 11 22 54 am" src="https://user-images.githubusercontent.com/35045729/34909338-2c65f588-f854-11e7-902f-252d8939134c.png">

**Comment by tmclean85** [comment]
Resolved all but Impact issue under merge commit 8eb470a 
Can't seem to replicate issue on Impact page??

**Comment by sovetsch** [comment]
All good when testing on desktop at various widths.
Issue when testing on an iPhone 7 Natively. Seems that get involved is getting cut off. 
![img_1594](https://user-images.githubusercontent.com/35045729/35602621-13ebee98-05ee-11e8-92e4-e3282129c7bf.PNG)

**Comment by tmclean85** [comment]
Confirmed final accordion viewport issue is still occurring, will resolve during back end of the week.
