### ISSUE TITLE
Home Page Pre-Footer Donate Button Text

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#124]
### Overview
It's going cray cray. It's outside the box...

### Tasks
- [x] Change text size in pre-footer to:
Mobile 16px
Tablet 20px
Desktop 32 px
- [x] Text in button:
Mobile 16px
Desktop 24px
- [x] Make sure all donate buttons open a new tab

**Comment by tmclean85** [comment]
Resolved under merge commit 0355882

**Comment by sovetsch** [comment]
Done. looks great!
