### ISSUE TITLE
About Page Bugs

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#125]
### Tasks
- [x] Vision menu item takes you to Philosophy of Care. Change this!
- [x] Leadership: images should be aligned to the top of the div
- [x] Headings need to be corrected, font size and style
- [x] Exemplified is spelled incorrectly in leadership header
- [x] Change "Brief History" => "History"
- [x] Report: PDFs open in the same page => change this to open in new tab

**Comment by tmclean85** [comment]
Resolved under merge request 60b0f1c

**Comment by sovetsch** [comment]
- [x] Philosophy of care heading needs to be same weight as other headings

- [x] Same with Leadership heading

- [x] report panel issue has been returned.
<img width="1088" alt="screen shot 2018-01-30 at 6 53 32 pm" src="https://user-images.githubusercontent.com/35045729/35602764-eea1e4d4-05ee-11e8-9c6f-413f50080e2b.png">

- [x] Please make sure the prefooter CTAs are consistent in their use of dropshadow on buttons and font-size and -weight. Below is a comparisons of About (top) and Home (Bottom). Lets keep the font-size and -weight on the about page but add the drop shadow as shown on Home.
<img width="1317" alt="screen shot 2018-01-30 at 6 56 11 pm" src="https://user-images.githubusercontent.com/35045729/35602846-42393c96-05ef-11e8-8287-a5f7eb2119ff.png">
<img width="1181" alt="screen shot 2018-01-30 at 6 51 41 pm" src="https://user-images.githubusercontent.com/35045729/35602852-47cecba8-05ef-11e8-8ca3-7deeab6028e1.png">

- [x] Add padding on the bottom of Mobile CTA at least same as padding-top
![img_1595](https://user-images.githubusercontent.com/35045729/35602911-a2e091d4-05ef-11e8-893a-b0aa58abfd8c.PNG)

- [x] Accordion still opens in the middle of the section

Thank you! @jesstice @tmclean85 @Coryjh85

**Comment by sovetsch** [comment]
Just the CTA situation is left outstanding. The rest is looking great! @tmclean85

**Comment by tmclean85** [comment]
Have you checked in the last 30 minutes or so? I did a bit of work on it that Jess just recently deployed.

**Comment by sovetsch** [comment]
See latest issue I posted, something funky is happening with the CTA's

**Comment by tmclean85** [comment]
Yep, I'm fixing them now. As this is the About page issue, can you review the About / NYC page as they share CTA's and work to them has been deployed. Then we can put the About page issue to bed.

**Comment by sovetsch** [comment]
Looks good except the drop shadow is still missing. Cleared cache and everything.

**Comment by sovetsch** [comment]
I am in bed :P

**Comment by tmclean85** [comment]
Oh I didn't catch that. I'll add the shadow. I'm running a little blind now since I can't access the invision prototypes. It notifies me that the prototype has put Erin over her limit and won't allow me to open anything. You don't have it hosted on your own invision account by any chance do you?

**Comment by sovetsch** [comment]
I shall add you to mine, what is your email?
Sorry I should have done that a while ago, totally forgot.

**Comment by tmclean85** [comment]
No worries, trevor.a.mclean@gmail.com

**Comment by sovetsch** [comment]
You seem to already have access to all three sizes. They are labeled A - Desktop, B - mobile, C - Tablet. I'll remove you and reinvite you.

**Comment by tmclean85** [comment]
I'll be up working for a couple hours, and I'll leave a message for Jess to deploy in the morning when she can. If you can squeeze it in maybe touch base with her to see when she's deployed and have a quick look at the issues we're looking at tonight.

**Comment by tmclean85** [comment]
Prototypes work now, thanks.

**Comment by sovetsch** [comment]
Sounds good, just re-added you to the InVision prototype. 
Thank you for all your hard work on this, appreciate the attention to detail you brought to this project.

**Comment by sovetsch** [comment]
Awesome! Let me know if you have questions.
