### ISSUE TITLE
NYC Fixes

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#129]
### Tasks
- [x] Sidebar stops in the wrong position (see comment below)
- [x] Mobile: Cannot navigate to top of NYC page (see comment below)

- [x] Partners section: need more spacing between logos so that they look distinct from one another, and they can also be made smaller – typically funders will have specifications about minimum white space surrounding their logo, and these are too squished together, especially on mobile/tablet.
  - [x] Padding
- [x] Sub-heading: Take out the period at the end. 
  - [x] On tablet (landscape), this gets bumped to two lines, and the lines are stacked too closely – add some padding between text lines here
- [x] Add bottom padding to the video
- [x] desktop: pre-footer text too big
- [x] desktop: reduce spacing between the points in the timeline section (> notes)
- [x] tablet: call to action banner height too large (see comment below for image)
- [x] tablet: "Planning and Development" heading to be hidden
- [x] tablet: "Timeline..." text and years should be shifted to the right a bit
- [x] tablet: Partnership logos should be 2x2
- [x] tablet: Pre-footer text and button should be side by side
- [x] mobile: Sub-heading and upper donation banner disappear on mobile => want to keep these
- [x] mobile: Stop the auto of the slider

**Comment by tmclean85** [comment]
Resolved with merge commit 549ca36

**Comment by jesstice** [comment]
Sidebar needs adjustment.
<img width="747" alt="screen shot 2018-01-29 at 9 06 50 pm" src="https://user-images.githubusercontent.com/19242967/35549055-5c6ec44e-0538-11e8-8492-750c0253ffb1.png">

**Comment by jesstice** [comment]
@tmclean85 When navigating on mobile, you are forced to click on "Vision" which brings you to the Vision section and skips the resources. If there isn't a way to click on "Native Youth Centre" to bring you to the page, maybe we should just add a menu link to "Resources". Thoughts?

**Comment by tmclean85** [comment]
Added 'Resources' to NYC menu, pushed anchor point code on cowboy commit 8c8fb8f
