### ISSUE TITLE
News Fixes

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#130]
### Tasks
- [x] Change to "Latest News" in the dropdown menu
- [x] Link to Categories in sidebar menu isn't working
- [x] Change "other news" to "more news"
- [x] Media section: Media in menus doesn’t jump to the section
- [x] desktop: page content overlaps with sidebar menu
- [x] Thumbnails are distorted
- [x] Link to external news should open new tab
- [x] pre-footer:
  - [x] tablet: overall height and text decrease in size, contact info arrangement fixed
  - [x] mobile: pre-footer text thickness should be decreased
- [x] mobile: remove image in the banner
- [x] mobile: remove gap at the bottom of the page
- [x] Resource slider on mobile: 
  - [x] stop the auto rotate of the slider
  - [x] Needs better navigation cues – three dots should indicate which news item user is currently viewing. Add arrows (or something similar) on the right and left of the image that will cue users to swipe.

**Once the right align is dealt with, check to make sure: Text snippet for news items doesn't overrun the “read more” link**

#### Single News Page
- [x] Change the CFS for the news text to remove the "50 words or less" part... cause it's obviously more
- [x] Include the back button to the main news page
- [x] Entire page should be styled like indiv. success stories page
- [x] Image!!! Way too big
- [ ] Change the CFS to add rich text editor for the main article text
- [x] Add date stamps
- [x] Check which article photo shows up (featured image or CFS) to make it clear for user
  - [x] Add instructions so it's clear => client is confused
- [x] Move categories right under title and date stamp

#### Categories
Flow: 
=> When you click on `Categories` in menu, should be taken to a page that displays all categories.
=> When on the categories page, clicking on a category should take you to a taxonomy archive page that displays all news posts with that category.
=> When on the main page, clicking on a category should take you to the taxonomy archive page that displays all the news posts with that category.

#### Media Inquiries
- [x] Remove text, should only be heading and contact info
