### ISSUE TITLE
Get Involved Fixes

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#131]
### Tasks
- [x] tablet: styling of Join/Donate section, covered by issue #90 
- [x] Join Us => Donate section:
  - [x] Heading up top should not be “join us” - should be “Donate” - think that is a vestige of a previous version. Also need to put a “Donate” button in this section.
  - [x] Remove photo
  - [x] Text left aligned
  - [x] Add `Donate` button
- [x] Employment Opps:
  - [x] Take out arrow, add "PDF" in brackets
- [x] Pre-footer:
  - [x] Remove drop shadow of button
  - [x] Add padding above section
  - [x] Change text to the following:
      - [x] Banner: Interested in partnering with one of our programs? Get in touch with our program staff to talk about how you can be involved.
    - [x] CTA: Explore Programs 
    - [x] Link: Programs page, land on top of “Check Out Our Programming” bar. 
- [x] Accordion Nav:
  - [x] Volunteer not accessible in menu
- [x] "i" section:
  - [x] currently hidden on mobile => should be viewable

**Comment by jesstice** [comment]
Can you close this, @Coryjh85?
