### ISSUE TITLE
Get Involved nav menu item not showing up on screen

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#177]
## Overview
“Get Involved” menu line is missing on:
o   Chrome, Samsung Galaxy S7
o   Safari, iPhone 5, iPhone 6, iPhone SE 5
o   Safari and Google, iPhone SE

## Tasks
- [x] Add media query for iphone devices
- [x] Add blue background, remove bkg from nav header
- [ ] Test:
  - [x] iphone 6, chrome safari
  - [x] iphone 8, chrome safari
  - [ ] iphone 7
  - [ ] Galaxy S7
  - [x] iphone SE 5

**Comment by jesstice** [comment]
Completed the CSS on this, I think. Just need to test across iphone devices.

**Comment by jesstice** [comment]
Should look like this:
<img width="316" alt="screen shot 2018-04-09 at 11 04 09 pm" src="https://user-images.githubusercontent.com/19242967/38538834-5e315e56-3c4a-11e8-82f4-c22cd2db5353.png">

**Comment by tmclean85** [comment]
I'm noticing on my galaxy s7 that it looks ok when the android nav bar isn't visible across the bottom, but if you scroll the screen and trigger the nav, the get involved link gets covered. Not too sure what to do to give it some breathing room down there, most of what's in the mobile footer seems pretty important. Thoughts?

**Comment by jesstice** [comment]
Okay, how about now @tmclean85? How does it look?
