### ISSUE TITLE
About page and Impact page image consistency

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#186]
## Overview
The images for the About and Impact page are not consistent. Also the sub-headings should be the same.

The About page has oval sized images:
<img width="968" alt="screen shot 2018-04-16 at 9 03 03 pm" src="https://user-images.githubusercontent.com/19242967/38848024-93beb2b6-41b9-11e8-8647-64dc58218684.png">

And the Impact page has much larger images:
<img width="943" alt="screen shot 2018-04-16 at 9 03 32 pm" src="https://user-images.githubusercontent.com/19242967/38848043-a92e850e-41b9-11e8-8eb3-8b9db937d507.png">

## Tasks
- [ ] Make About page images circle
- [ ] Adjust sizing of Impact page to be more aligned with About page
- [ ] Fix sub-heading for Impact page
