### ISSUE TITLE
Get Involved Page layout & CSS

### ISSUE THREAD

**Issue by jesstice** [redacademy/unya-spring-2017#90]
## Overview
Get Involved page needs to align with the Invision design.

## Tasks
- [x] Remove red diagonal
- [x] Change "Donate" to "Join Us"
- [x] Move the image in the Join Us/Donate section to the left side
- [x] Remove call to action banner
- [x] Update CSS for opportunities to match
- [x] Add button to pre-footer
- [x] Align pre-footer text to the left
- [x] Remove 2nd instance of "Please email info@unya..."

**Comment by jesstice** [comment]
2nd instance: 
<img width="1100" alt="default" src="https://user-images.githubusercontent.com/19242967/34082489-241e3dcc-e314-11e7-86ca-ac29cbf406f9.png">

**Comment by tmclean85** [comment]
Resolved with merge commit 9314cf9
